# https://spring.io/guides/gs/spring-boot-docker/

FROM openjdk:8u131-jre-alpine

VOLUME /tmp
COPY server/target/server-0.0.1-SNAPSHOT.jar /app.jar
RUN sh -c 'touch /app.jar'
EXPOSE 8080
ENV JAVA_OPTS=""
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
